In [1]:
import numpy as np

In [5]:
np1 = np.array([[1,2,3,4], [1,2,3,4]])
np1.ndim, np1.shape

(2, (2, 4))

In [6]:
np1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [14]:
np1 = np.array([[[1,2,3,4],[2,4,6,8], [3,6,9,12]], [[4,8,12,16], [5,10,15,20], [6,12,18,24]], [[7,14,21,28], [8,16,24,32], [9,18,27,36]]])
np1.ndim, np1.shape

(3, (3, 3, 4))

In [15]:
np1

array([[[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12]],

       [[ 4,  8, 12, 16],
        [ 5, 10, 15, 20],
        [ 6, 12, 18, 24]],

       [[ 7, 14, 21, 28],
        [ 8, 16, 24, 32],
        [ 9, 18, 27, 36]]])

#### Layer1 has
#### [1,2,3,4]
#### [2,4,6,8]
#### [3,6,9,12]

#### Layer2 has
#### [4,8,12,16]
#### [5,10,15,20]
####  [6,12,18,24]

#### Layer3 has
#### [7,14,21,28]
#### [8,16,24,32]
#### [9,18,27,36]
##### In case of 3 dimensional array, Axis is the layer. Axis 0 is Layer 1, Axis 1 is Layer 2, Axis 2 is Layer 3


In [ ]:
np1[:,:,1] *=2

#### Multiplying the 2 column on each axis with 2 and broadcasting. This will be an inplace update. As in the np1 will get updated automatically. As can be seen below

In [49]:
np1

array([[[ 1,  4,  3,  4],
        [ 2,  8,  6,  8],
        [ 3, 12,  9, 12]],

       [[ 4, 16, 12, 16],
        [ 5, 20, 15, 20],
        [ 6, 24, 18, 24]],

       [[ 7, 28, 21, 28],
        [ 8, 32, 24, 32],
        [ 9, 36, 27, 36]]])

In [63]:
np1 = np.array([[[1111, 1211, 1311], [2111, 2211, 2311], [3111, 3211, 3311]], [[1121, 1221, 1321], [2121, 2221, 2321], [3121, 3221, 3321]], [[1113, 1213, 1313], [2113, 2213, 2313], [3113, 3213, 3313]]])

In [64]:
np1

array([[[1111, 1211, 1311],
        [2111, 2211, 2311],
        [3111, 3211, 3311]],

       [[1121, 1221, 1321],
        [2121, 2221, 2321],
        [3121, 3221, 3321]],

       [[1113, 1213, 1313],
        [2113, 2213, 2313],
        [3113, 3213, 3313]]])

#### Selecting only 2nd row from each axis

In [66]:
np1[:,1:2,:]

array([[[2111, 2211, 2311]],

       [[2121, 2221, 2321]],

       [[2113, 2213, 2313]]])

#### Selecting only 2 column from each axis

In [67]:
np1[:,:,1:2]

array([[[1211],
        [2211],
        [3211]],

       [[1221],
        [2221],
        [3221]],

       [[1213],
        [2213],
        [3213]]])

In [76]:
np1[1:2,:,:]

array([[[1121, 1221, 1321],
        [2121, 2221, 2321],
        [3121, 3221, 3321]]])

#### When slicing a 3 dimensional numpy array.
#### . 1st parm is the axis
#### . 2nd parm is rows
#### . 3rd parm is columns

In [77]:
# Selecing the 
np.array([[[1,2,3,4],[2,4,6,8], [3,6,9,12]],
                [[4,8,12,16], [5,10,15,20], [6,12,18,24]],
                [[7,14,21,28], [8,16,24,32], [9,18,27,36]]])[1:2,:,:]

array([[[ 4,  8, 12, 16],
        [ 5, 10, 15, 20],
        [ 6, 12, 18, 24]]])

In [79]:
np1 = np.array([1,2])
np.sum(np1, axis=0)

3

In [87]:
np1 = np.array([[1,2],[3,4]])
np.sum(np1, axis=0)
#### 1+3 = 4
#### 2+4 = 6

array([4, 6])

In [85]:
np1.ndim

2

In [89]:
np1 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
np1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [90]:
np1.ndim

3

In [92]:
np.sum(np1, axis=0)
#### 1+5, 2+6
#### 3+7, 4+8

array([[ 6,  8],
       [10, 12]])

In [95]:
np1 = np.array([[[1,2,3,4],[2,4,6,8], [3,6,9,12]],
                [[4,8,12,16], [5,10,15,20], [6,12,18,24]],
                [[7,14,21,28], [8,16,24,32], [9,18,27,36]]])

In [98]:
np.sum(np1,axis=0)

array([[12, 24, 36, 48],
       [15, 30, 45, 60],
       [18, 36, 54, 72]])

In [99]:
np.sum(np1,axis=1)

array([[ 6, 12, 18, 24],
       [15, 30, 45, 60],
       [24, 48, 72, 96]])

In [100]:
np.sum(np1,axis=2)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [101]:
np1 = np.array([[[1111, 1211, 1311], [2111, 2211, 2311], [3111, 3211, 3311]], [[1121, 1221, 1321], [2121, 2221, 2321], [3121, 3221, 3321]], [[1113, 1213, 1313], [2113, 2213, 2313], [3113, 3213, 3313]]])

In [102]:
np1.ndim

3

In [103]:
np.sum(np1, axis=0)

array([[3345, 3645, 3945],
       [6345, 6645, 6945],
       [9345, 9645, 9945]])

In [104]:
np.sum(np1, axis=1)

array([[6333, 6633, 6933],
       [6363, 6663, 6963],
       [6339, 6639, 6939]])

In [105]:
np.sum(np1, axis=2)

array([[3633, 6633, 9633],
       [3663, 6663, 9663],
       [3639, 6639, 9639]])

In [106]:
np1

array([[[1111, 1211, 1311],
        [2111, 2211, 2311],
        [3111, 3211, 3311]],

       [[1121, 1221, 1321],
        [2121, 2221, 2321],
        [3121, 3221, 3321]],

       [[1113, 1213, 1313],
        [2113, 2213, 2313],
        [3113, 3213, 3313]]])

In [109]:
np1[:,:,1:2]

array([[[1211],
        [2211],
        [3211]],

       [[1221],
        [2221],
        [3221]],

       [[1213],
        [2213],
        [3213]]])

In [111]:
np1[:1,:,:]

array([[[1111, 1211, 1311],
        [2111, 2211, 2311],
        [3111, 3211, 3311]]])

In [112]:
np1[:,1:2,:]

array([[[2111, 2211, 2311]],

       [[2121, 2221, 2321]],

       [[2113, 2213, 2313]]])

In [120]:
np.random.random((10)).ndim, np.random.random((10))

(1,
 array([0.86372211, 0.83111962, 0.26968197, 0.58514718, 0.41967684,
        0.50021254, 0.49772433, 0.01441052, 0.16743967, 0.11153065]))

In [121]:
np.random.random((10, 1)).ndim, np.random.random((10, 1)).shape, np.random.random((10,1))

(2,
 (10, 1),
 array([[0.65232896],
        [0.85042197],
        [0.13014264],
        [0.18063091],
        [0.26226207],
        [0.73736507],
        [0.01079701],
        [0.53423628],
        [0.89105763],
        [0.96577352]]))

In [122]:
np.random.random((10, 10)).ndim, np.random.random((10, 10)).shape, np.random.random((10,10))

(2,
 (10, 10),
 array([[0.45542286, 0.84178984, 0.78970991, 0.05722003, 0.90142067,
         0.13192809, 0.7854133 , 0.8831912 , 0.56689139, 0.05484798],
        [0.22089242, 0.33049955, 0.10062658, 0.40285053, 0.84812042,
         0.33276084, 0.62569795, 0.19183988, 0.03721818, 0.55803601],
        [0.26830872, 0.3973961 , 0.6058502 , 0.93071515, 0.42453603,
         0.47890097, 0.04664342, 0.23954268, 0.933911  , 0.25150725],
        [0.92674811, 0.53257118, 0.60858797, 0.99266604, 0.68745027,
         0.81684198, 0.28606679, 0.6254673 , 0.83325168, 0.0138153 ],
        [0.92813611, 0.23874325, 0.83431215, 0.2859501 , 0.22111718,
         0.87371192, 0.52002691, 0.71616507, 0.47265191, 0.71617122],
        [0.62197322, 0.47725364, 0.97079695, 0.00152843, 0.77280048,
         0.37426318, 0.01960999, 0.76812789, 0.81591978, 0.11250757],
        [0.44274391, 0.9139934 , 0.20831271, 0.74971013, 0.76635877,
         0.05939085, 0.24200327, 0.28983953, 0.17960878, 0.34224529],
        [0.5

In [123]:
np.random.random((10, 10, 10)).ndim, np.random.random((10, 10, 10)).shape, np.random.random((10,10, 10))

(3,
 (10, 10, 10),
 array([[[5.64241396e-01, 2.25299764e-01, 3.79473001e-01, 2.61071472e-01,
          9.14891093e-01, 3.18371612e-01, 8.05255846e-01, 6.77439030e-01,
          3.91533561e-01, 6.95262148e-01],
         [7.79887714e-01, 4.15722500e-01, 2.21974825e-01, 6.73316593e-01,
          1.35489155e-01, 2.87975630e-01, 6.28796960e-01, 8.23241527e-01,
          4.40244335e-01, 3.03579166e-01],
         [7.33997290e-01, 4.16750021e-01, 3.65430995e-01, 1.70112884e-01,
          4.70055634e-01, 8.09360942e-01, 8.42920987e-01, 2.38499104e-02,
          2.49708735e-01, 7.76034003e-01],
         [9.00954298e-01, 8.10905617e-01, 8.69893603e-01, 1.07234942e-01,
          6.08917961e-01, 2.99625881e-01, 4.73665512e-01, 8.97462073e-01,
          6.75774437e-01, 1.99336205e-01],
         [5.25295878e-01, 5.05101593e-01, 5.20699344e-01, 5.11521733e-01,
          6.72124862e-01, 8.22693162e-01, 5.66903360e-01, 9.90729190e-01,
          1.04654135e-01, 9.50407308e-01],
         [1.18407329e-01, 

In [124]:
np1.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [135]:
x = np.random.rand(100,10)
y = x[:5, :]
x[:5, :]

array([[0.61010206, 0.30227079, 0.62596605, 0.55447325, 0.00459308,
        0.67164129, 0.55519858, 0.04115527, 0.75099382, 0.66185364],
       [0.30942437, 0.36360192, 0.99043327, 0.14575947, 0.00856511,
        0.36896393, 0.24319782, 0.00541383, 0.57825088, 0.32743562],
       [0.10573577, 0.4683061 , 0.1446194 , 0.69205797, 0.13956902,
        0.51072638, 0.33375712, 0.75716606, 0.55756719, 0.04417139],
       [0.01378515, 0.20886627, 0.68321877, 0.39804269, 0.93206161,
        0.63215939, 0.67357866, 0.9989293 , 0.51779199, 0.39541802],
       [0.9650628 , 0.40216079, 0.0692596 , 0.83508954, 0.2112084 ,
        0.216158  , 0.95483147, 0.79862865, 0.63150675, 0.596068  ]])

In [136]:
y[:] = 0
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [137]:
x[:5, :]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [138]:
np.may_share_memory(x,y)

True

In [139]:
x = np.random.rand(100,10)
y = x[:5, :].copy()
x[:5, :]

array([[2.73318022e-01, 3.39045430e-01, 7.22581013e-01, 4.38960532e-01,
        3.19285833e-01, 7.53036492e-01, 7.76399558e-01, 9.12916245e-02,
        2.22029088e-01, 1.10223649e-01],
       [3.72261413e-01, 7.40464219e-01, 5.70831386e-01, 7.98578104e-02,
        2.33372063e-01, 5.98986295e-01, 1.86166849e-01, 7.28166619e-01,
        3.15665717e-04, 7.93633072e-01],
       [5.63216699e-01, 1.96973957e-01, 5.46481633e-02, 4.87241356e-01,
        4.57723053e-03, 3.01133518e-01, 3.36583954e-01, 9.97868474e-01,
        1.20463788e-01, 9.94419668e-01],
       [6.77820063e-01, 2.85624763e-01, 9.27881324e-01, 9.45194773e-01,
        8.12282461e-01, 1.38741703e-01, 1.95747994e-01, 5.80236157e-01,
        3.60710301e-01, 5.00095105e-01],
       [2.69075457e-02, 5.95903589e-01, 5.33450835e-01, 4.56638326e-01,
        4.02233760e-01, 1.76233302e-01, 8.24736908e-01, 3.39858889e-02,
        3.41314363e-01, 3.87042956e-01]])

In [140]:
y[:] = 0
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [141]:
x[:5, :]

array([[2.73318022e-01, 3.39045430e-01, 7.22581013e-01, 4.38960532e-01,
        3.19285833e-01, 7.53036492e-01, 7.76399558e-01, 9.12916245e-02,
        2.22029088e-01, 1.10223649e-01],
       [3.72261413e-01, 7.40464219e-01, 5.70831386e-01, 7.98578104e-02,
        2.33372063e-01, 5.98986295e-01, 1.86166849e-01, 7.28166619e-01,
        3.15665717e-04, 7.93633072e-01],
       [5.63216699e-01, 1.96973957e-01, 5.46481633e-02, 4.87241356e-01,
        4.57723053e-03, 3.01133518e-01, 3.36583954e-01, 9.97868474e-01,
        1.20463788e-01, 9.94419668e-01],
       [6.77820063e-01, 2.85624763e-01, 9.27881324e-01, 9.45194773e-01,
        8.12282461e-01, 1.38741703e-01, 1.95747994e-01, 5.80236157e-01,
        3.60710301e-01, 5.00095105e-01],
       [2.69075457e-02, 5.95903589e-01, 5.33450835e-01, 4.56638326e-01,
        4.02233760e-01, 1.76233302e-01, 8.24736908e-01, 3.39858889e-02,
        3.41314363e-01, 3.87042956e-01]])

In [142]:
np.may_share_memory(x,y)

False

In [147]:
list(range(1,5,2))

[1, 3]

In [151]:
np.arange?


Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [1]:
import numpy as np

In [2]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method

In [4]:
[x for x in dir(np.random) if not x.startswith("_")]

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'weibull',
 'zipf']

In [26]:
np.random.rand(1,6)

array([[0.2665095 , 0.47364555, 0.1460495 , 0.47879077, 0.3891347 ,
        0.21402866]])

In [18]:
2.5 * (np.random.randint(1,5,size=(5)) - 1)/4

array([0.   , 1.875, 0.625, 0.   , 0.   ])

In [17]:
2.5 * (np.random.random_integers(5, size=(5,)) - 1) / 4

/var/folders/y2/ff1bp6sj4hq36hkps05494740000gn/T/ipykernel_12439/2420679119.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  2.5 * (np.random.random_integers(5, size=(5,)) - 1) / 4


array([1.25, 2.5 , 0.  , 1.25, 1.25])

In [23]:
np.mean(np.random.rand(1,10))

0.5306348963026516

In [43]:
np_normal = np.random.normal(0,1,(100,1))
np.mean(np_normal), np.std(np_normal)

(0.05012758929585118, 0.8951868191773051)

In [45]:
np.zeros((3,1),dtype=int)

array([[0],
       [0],
       [0]])

In [46]:
np.zeros((3,1),dtype=float)

array([[0.],
       [0.],
       [0.]])

In [48]:
np.eye(3,3,0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.ones((1,5),dtype=int), np.ones((1,5),dtype=float)

(array([[1, 1, 1, 1, 1]]), array([[1., 1., 1., 1., 1.]]))

In [59]:
np.linspace([2,3], [2,4], num=5,retstep=True, endpoint=False, axis=0)

(array([[2. , 3. ],
        [2. , 3.2],
        [2. , 3.4],
        [2. , 3.6],
        [2. , 3.8]]),
 array([0. , 0.2]))

In [66]:
np.linspace([[1, 2, 1], [3, 4, 2]], [[5, 6, 7], [7, 8, 9]], num=5, retstep=False,axis=1)

array([[[1.  , 2.  , 1.  ],
        [2.  , 3.  , 2.5 ],
        [3.  , 4.  , 4.  ],
        [4.  , 5.  , 5.5 ],
        [5.  , 6.  , 7.  ]],

       [[3.  , 4.  , 2.  ],
        [4.  , 5.  , 3.75],
        [5.  , 6.  , 5.5 ],
        [6.  , 7.  , 7.25],
        [7.  , 8.  , 9.  ]]])

In [78]:
np.array(["hello1", "world1"],dtype=str).dtype

dtype('<U6')

In [79]:
x = np.array([1,2,3,4])
x+1

array([2, 3, 4, 5])

In [82]:
x = np.array([[[1,2,3,4],[1,2,3,4]], [[5,6,7,8],[5,6,7,8]], [[9,10,11,12],[9,10,11,12]]])
x+1

array([[[ 2,  3,  4,  5],
        [ 2,  3,  4,  5]],

       [[ 6,  7,  8,  9],
        [ 6,  7,  8,  9]],

       [[10, 11, 12, 13],
        [10, 11, 12, 13]]])

In [83]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
x+y

array([ 6,  8, 10, 12])